version: 2
updates:
  # 1. NPM packages (Angular, TypeScript, etc.)
  - package-ecosystem: "npm"
    directory: "/"  # Root directory where package.json is located
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"

  # 2. GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of .github/workflows
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
